//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSignReformed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class citizen
    {
        public long adno { get; set; }
        public string email { get; set; }
        public string naam { get; set; }
        public string addr { get; set; }
        public long pno { get; set; }
        public Nullable<int> nooffiles { get; set; }
    }
}
